### PR TITLE
Require

### PR DESCRIPTION
**Pull request by echicken**

### CODE REVIEW

**Comment by tracker1** [comment]
why the changes from `const` to `var`?

**Comment by echicken** [comment]
Synchronet's webserver may reuse the same JS context across several requests from the same client.  If `const` is used at the top level of a script, and then a script called by the client on a subsequent visit (before some timeout) tries to declare a `const` of the same name, a redeclaration error will occur.

I was using `const` out of habit while writing and revising some scripts, then had to hunt down the source of resulting errors.  I'd assumed a clean global scope per request, but this is not the case.  Apparently this offers a big performance boost and won't be changed.

I modified my webserver locally to create a new context for each request, which worked very well, I abandoned that approach since it's unlikely to be adopted elsewhere.  Wrapping any top-level SSJS (or XJS) inside an IIFE can work around this, but this seemed clunky and hacky, and sacrifices any performance gains from this context reuse.

Use of `const` remains okay within functions/closures, but at the top level, `var` is safest.  Use of `const` at the top level may be okay in conjunction with Synchronet's `require` method (not the same as `require` in node.js), so I will have to experiment with that.  I'll be keeping this in mind in the near future when I restructure the reusable code (stuff in `web/lib/`), and how it's loaded and used.

**Comment by tracker1** [comment]
Wasn't sure if it was intended to be global.  Thanks for explaining. Aside, would `let` work in the context... only asking as I tend to consider var a cold smell for stuff that should be refactored slightly.  I really need to get back into how sync has or hasn't changed in the past few years.

**Comment by echicken** [comment]
Synchronet is using [SpiderMonkey 1.8.5](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Releases/1.8.5) circa 2011, so we have `var` and `const` but no `let`.

(Interestingly, Mozilla's [JavaScript 1.7](https://developer.mozilla.org/en-US/docs/Web/JavaScript/New_in_JavaScript/1.7) introduced `let` (I think) as an experimental feature which needed to be enabled at build time.  The implementation differed from what got proposed for ES6, so around 2014 `let` was [dropped](https://bugzilla.mozilla.org/show_bug.cgi?id=1023609) (and presumably reintroduced later on).  So it's possible this non-compliant `let` could be enabled in Synchronet (if I'm reading things right), but even if we turned it on it wouldn't quite be the `let` we know today.)

Like you I do a lot of work with node.js.  Going back to BBS stuff is like stepping into a JS time machine.  Synchronet's JS codebase reeks of code smell by the standards of today's JS dev, for a bunch of reasons we could discuss at great length.  There are quirks and oddities that can bite you unexpectedly (the context reuse mentioned above, among others).

When I see `var` in some old thing I wrote, or evidence of my earlier style, it signals potential problems and inefficiencies and I want to refactor everything.  With Synchronet stuff, I have to remember to be a bit more cautious in how I do that.  There's a bunch of stuff I'd like to tidy up in this project - I started it 4+ years ago after all - but if/when I tackle it, it'll have to be done carefully.

**Comment by tracker1** [comment]
It's funny, I worked on a project about 2 years ago now that was automating Adobe InDesign, which uses a really old variant of ES3, had to customize a LOT to get some kind of tooling for something resembling a modern workflow with Webpack.  It was pretty painful, but got around a lot of it at the time.  Had given thoughts of doing similar with sync to bring in something similar to CommonJS, but seeing the new require function, not sure if/how that would even work now.

Would love to see a Sync fork just use Node as the baseline, but know that won't happen.  Have been following Enigma loosely as well.

**Comment by echicken** [comment]
I remember having to do some work in ActionScript some years ago, and IIRC that was roughly ES3.  I started learning JS with Synchronet, but have worked with it in a bunch of different environments now (browsers, node, Rhino, espruino, some others).  I think there are fewer quirky differences between all of these nowadays, but jumping between them all had its challenges.

At one point I considered implementing a bunch of the node.js standard API for Synchronet to see if I could get at least some simple modules working in both.  We *could* have an event loop, but it might be insane.  I'm not sure if our `require` can be overridden, but maybe that's a thing.  A lot of the work would just be wrapping Sync's own methods.

Semi-relatedly, it might be possible to use babel or something to transpile more modern JS into something Synchronet can handle.

I haven't taken a close look at Enigma, but I like the idea.  I should really check it out at some point.  I've thought about starting my own project from time to time, but it's got to be a lot of work getting from nothing to some sort of usable BBS.  And for all that its JS environment is showing some age, I still like Synchronet a lot.

**Comment by tracker1** [comment]
I like Synchronet a *lot* as well.  Been thinking about either taking your API bits, or maybe redoing parts, and putting the sync server on a different port and running a front end with node in front of it... replacing parts of it with creating read then write interfaces for node to use against the actual sync data on disk.  I did quite a bit of this for C# on an old front end I had done, but not even sure I have the source for it anymore.  Mostly user and node/status data, had started parsing the scfg config stuff too, but just stalled out on it.

My original VM corrupted around 2013, and I really haven't had a stable board up since then.  I've re-setup a few times, and then down again since then.  It's sometimes hard to find motivation to work on these things on free time when it's what you do at work too...

FYI, I'm tracker1 on twitter and aztracker1 on fb if you want to chat more directly.

**Pull request merged**
