### PR TITLE
Convert to hacky single page app.  Improve fTelnet experience on mobi…

### PR DESCRIPTION
**Pull request by chairmanmow**
…le/tablet.  Refactor for responsiveness. UX enhancements.  Desktop terminal isn't rendering right.

### CODE REVIEW

**Comment by chairmanmow** [comment]
oops didn't mean to pull in to your branch

**Comment by Android8675** [comment]
Could you branch eChickens code and add your changes? I'd like to try this, I'm having fTelnet issues I can't track down the problem, though I suspect it's not the web interface, but something else blocking communications. At any rate I'd like to check out your changes.

**Comment by chairmanmow** [comment]
Yeah, I'll do that, I've got a few changes I need to push up though, but should be done by tonight.  I'll try to ping you after I've complete that.

**Comment by chairmanmow** [comment]
@Android8675 If you want to check it out, head over to https://github.com/chairmanmow/synchronet-web-v4 ... master branch is up to date with changes i've made and there's a read me specific to my fork.

**Comment by Android8675** [comment]
Cool, gonna check it out tonight. Thanks.

**Pull request closed without merging**
